version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - navid.shariaty
    labels:
      - dependencies

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - navid.shariaty
    labels:
      - dependencies
