---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gitopssecret-snappcloud-io-v1alpha1-sopssecret
  failurePolicy: Fail
  name: msopssecret.kb.io
  rules:
  - apiGroups:
    - gitopssecret.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sopssecrets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gitopssecret-snappcloud-io-v1alpha1-sopssecret
  failurePolicy: Fail
  name: vsopssecret.kb.io
  rules:
  - apiGroups:
    - gitopssecret.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sopssecrets
  sideEffects: None
