# permissions for end users to edit gpgkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpgkey-editor-role
rules:
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - gpgkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - gpgkeys/status
  verbs:
  - get
