# permissions for end users to view gpgkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpgkey-viewer-role
rules:
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - gpgkeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - gpgkeys/status
  verbs:
  - get
