# permissions for end users to edit sopssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sopssecret-editor-role
rules:
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - sopssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - sopssecrets/status
  verbs:
  - get
