apiVersion: gitopssecret.snappcloud.io/v1alpha1
kind: SopsSecret
metadata:
    name: example-sopssecret
    namespace: default
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    gpg_key_ref_name: gpgkey-sample
    secretTemplate:
        name: ENC[AES256_GCM,data:tEBmzhJbodOA76g=,iv:6//MD4pDQfIy8Kv78hclFvNV66TtoMHjfvuEpz+e0S4=,tag:4ipcrSNzT0hC2AbwFVOM3g==,type:str]
        labels:
            label1: ENC[AES256_GCM,data:y8KHycCN,iv:oKHcGLt7Jebw2RgvM2Qt2Io2JLuNaIQaKGRc2VORoSU=,tag:vIzI6DZuxbuV9NYlxtH6pw==,type:str]
        annotations:
            key1: ENC[AES256_GCM,data:uYGKNxKR,iv:9SV+4fo953YWpNF7OJ1omlDLFqdzIa5FZgMB44ByoRI=,tag:IciLh0ZnOqXu4s5h37ifrQ==,type:str]
        stringData:
            data-name0: ENC[AES256_GCM,data:6qkxKf4JgwjKI/U=,iv:yTBuOJXE5LdS3pLoMK471jvJCJ/tbB8ThMBGDMyAVLo=,tag:z6WPut+ao+icvduPfOhyFA==,type:str]
        data:
            data-name1: ENC[AES256_GCM,data:85nJ+u9Y7ZuPn1RbFriR7A==,iv:AF9jEf1N7cFzbtsaCU3j2+LEaxY2fgBZwE9/dW1aDAo=,tag:7TijpGr/X+ZSFEPQ637Tvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-23T05:24:52Z"
    mac: ENC[AES256_GCM,data:Hp1SMmxPoNp69WgzclSQejsAwXKoaFJpH7jbOrIP1caDodbw2XY3tEU6KiWKwzK85OFS3+VLKFKyUsjOxEGFk0dr0jMGHoZVkVp3N9lbIM5evkYKv7fwyNLv4wevdNZJenTUHavzmY7hwmB8i4VklOm3ZoN6k4j+Srnub+C+6UE=,iv:zIwLmq+e6vxNkb+59ZYsCa/Bibw2TZw6mXYl0IqEkRg=,tag:jvrP8zZg1kBcbtjHsvujfw==,type:str]
    pgp:
        - created_at: "2022-07-23T05:24:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA1lXVE3eM3FuAQwAo9eF9/ZWev2YyTBL2X0H7Mpjy4fl5iU+kNEpewCiriJF
            XKnaEBtFwYtfCnSdwePL2kmHYtZQYizZHltzfJXcmRNv/Slg5ud+bWfqmuDYyYyW
            4Fz0IHoJNtbOsyKZbtN0o0UGklKeREgj/gVYJaJMHzxNni+NNfZbZPGB/F35mD0k
            jNo2SzsNOIuOcEUps4DqNyfvJrTZzGXS8iCbOTOQq9L/9Q50FmEnyODU5V7Opw+m
            zUlEEBa5QluaS9idXuoYE3wEU0gdKLxoNHtGBhmzX2WNs8fc4rzh5FawU7A2UaAd
            HA4+cnfWwkVVVdmo57gFCoBFJYu3oS+04rdRT8PBkbDYokMmQH36SJdW8lm2bXW8
            BJovNIlO5ap1JDXgi8sAwV3naeNTyk9fwJe7bifnJBZNl1lRSnMUBM/mOOnCw+Gi
            fND8WHZf2k9yKt53ixYE4ru5gFaHBTT/prHtQ5/2hMYL/Frd5rQGHiS2paWbuDXU
            tqj2KXLditkSFmraqxNJ1GgBCQIQepmpMZCaP3RALowvpxnCh47koRfkUFj9SmcZ
            YtB3RZwpcVAB+x1b8aF7BHqHQ5xlGN1Ne/wwOE9Q0NnQoXX3Y5YugvDr5rDB1dRQ
            ftggTuaiyeyeIcyztvWKQHnIc8VuNdinLQ==
            =3hwF
            -----END PGP MESSAGE-----
          fp: 0DCAB05D8154DFF66266FD1D32E6EC2AD915FA4D
    encrypted_suffix: secretTemplate
    version: 3.7.2
