apiVersion: gitopssecret.snappcloud.io/v1alpha1
kind: SopsSecret
metadata:
    name: example-secret
    namespace: default
    labels:
        key_label1: label_value1
    annotation:
        key_annotation1: value_annotation1
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    gpg_key_ref_name: gpgkey-sample
    stringData:
        data-name0: ENC[AES256_GCM,data:PmuiVIg4F9dQhIQ=,iv:tEDOolEUsPzrA+Wzp9Lb3IICIDQ6Jvw8RoI552/mQWE=,tag:i4sHuhcpFcn2HyQwYVGf9Q==,type:str]
        data-name1: ENC[AES256_GCM,data:0XCSZ6BPQSRZrf4=,iv:epIbC+eGsk7GKZ/N/MFydSsRzz16opo+tNSCX8xwG1w=,tag:nwa58+H3D93E61gheQ3esw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-26T12:26:16Z"
    mac: ENC[AES256_GCM,data:2VNCvvoQ/5QAbOhi+gTGeS0+wcODVtTwYUb2lTcWuc64uQC2ioJLuVp16DVkrCNieCrRd3+tK3JBDFThj8MHDAnb1kyUkSjuw5ZReoRWuPG3wsPmuPkaZ+4SdJgvzdslEDvyEcLnXe1ow6INEBVjVFOuEBPmqb7JSPzIEG8ACCg=,iv:vhfDw1T317dr970zr1KtwQGydc792hY4xOmup0OHfow=,tag:IkFekcqAxWSVH34M2XGEgQ==,type:str]
    pgp:
        - created_at: "2022-07-26T12:26:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0IdHboLn5ZuARAAkhHicVaHQlA7D0HPJT0/Z1a3TP855wQClAtQt+cM6jiU
            Rz7W13h2hjN21o+6IWWZV5ITA2zlIKLE0isz8peQ8wIgLZ96dl6N3DR0z/xM4Gr2
            /GylQOxR6kewHYD/H2/FTJXeZ9q1bIk7wCi2RLXTQtM8KPyxiBPNbzb57QYUL/vo
            WsoflVma10B1kZZuEl3g9HvmldF2FTysSBKbzTaQhkPIeezhZYAddkSeoZnNF5HA
            4BqeN30W6BJYqHfcI0bbyzT9c3vh4KSgn0SVMlbAqxNFedUDhk+r1d3Q5/3Q7E50
            4Xq5jtpD09sva+8wxQfN3NmsZZJSDujwwPHziN88EbDT+yR6WZz2TdVjsgBl1W2h
            0KAdou8rzXn3Iiib6yRtzvMYrvRJCJYBul/YZcvD8U/mpgRORXlC6USowkh+nDbL
            Yl97JZEMJy1AVys3s6l1I6MFcuiez3BH80E0EvwHFxW//fpIP56eOEX2CAsCYglw
            hKcwpb683zfikXo7NPt4G/pGx09xQha4NpBU1ZK95B/z+XKsEEJY0cdcFsE+bXZK
            ZGxaCDn2aNxTghEBUzinAEsQ+GkIyeZw+vNvL3x2v+3h2JjiUBuCqxBfQZ127CGH
            1z6M1RlaoCqwcttz9IHNObBZ4bBnjaqHENzz0Qr1QWW9vVltit+e3fPZY5I1bFHU
            aAEJAhDduTWxx3JMQWnJXqExQUScdS19n5pb2QQ4lwRVQ0Z8QOblQjlb67cN4NjJ
            0hBZ5auKDhEcfCtzLEQ8P2fu9hC5XsXsYrdsz1SGpiLL5fipy0CQxFWp71DusSsJ
            fWmBLgUYyIi2
            =oNhH
            -----END PGP MESSAGE-----
          fp: 32B974509BC4B9DD570AB0E8067EBF5DA6F0220A
    encrypted_suffix: stringData
    version: 3.7.2
