apiVersion: gitopssecret.snappcloud.io/v1alpha1
kind: SopsSecret
metadata:
    name: example-secret
    namespace: default
    labels:
        key_label1: label_value1
    annotations:
        key_annotation1: value_annotation1
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    gpg_key_ref_name: gpgkey-sample
    stringData:
        data-name0: ENC[AES256_GCM,data:PwCkokrGeDFj53c=,iv:G2WuV+vnc87PGUU/UGYmgKA/1gIj2qG6x9uzpXNIisw=,tag:ENd3MqmLjBV2PXjC20rVQA==,type:str]
        data-name1: ENC[AES256_GCM,data:PCt+ETH/ZBrJy5g=,iv:zuzBiREQjIoM6DxyE9ItT2HAnKo5CC8t7goCJM7/a84=,tag:I81LFKsYAuVLFO1AxmikqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-03T20:45:40Z"
    mac: ENC[AES256_GCM,data:hLFwnYB5H1O7TPaKTCGG4/t+tnf1IBsBtr3+02NJwCk88XtXrrQJCR0ys//K2NVjXcKPBS+Mgj/JhMovcCzMAXQeCqgoBRM8rd9d6eC0KTxmlkcG17UTQM5uk94RQ4gMN/kjBAcxG51rTR9tJq/Ej0kEEkVI0/hEss+8m9a6A/Q=,iv:B0hfUu1Io5zEJBNtSKFJXtJ3ZhfUqtbOsFd2hWICULE=,tag:niwFYglf/BFwg4NGezq0dQ==,type:str]
    pgp:
        - created_at: "2022-08-03T20:45:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0IdHboLn5ZuAQ//eolCKdJaHEmz7sf6I8BNgcLpWsRRkLqasopnFBN9eKbu
            pUwP+BNuiV89lzZnRMDOPdXNVyxI/OEyKYCH9ohdGKJ3ssAB5y1oXWYAsGf5Z+0P
            QX9Vn1b+MmXS274DadlhpPWjDli+b/MKGpyb45v4zLEZBOayCiE9uB/JSi+zNcCy
            p+AYaHCoEI+lpUn/RkVci1HftIM+MfRHlggPvcUiig5jAelqyBndz3irmm56Ev1F
            dCo5TsUB3dOnazZZIxlSEIOdRn582jOEWxysHoFgaFz5XqiqpG9NOVoV+yUK9q4i
            hmWn2VPUqcJ9Q2U04UBshZeI86Ao6KlVJoSII2Z7wB2fhefU1h0cvI2kqKg3bpGp
            hka3TKNkGKtCU5a8kEH4JXjCv6fbEx+zjtoWUdiW1xvMkLWZ/jLSG9MEq68SWpi2
            yWad3/gsYwQ688EwKmRfyS3I73letq/JgcWnqTjLX8MBEHuqWMgYnblzb7ypVJRX
            j4y8b1xeHFSzAEut0mdr+41q52EnN23uGtGy/u/SqyQcR4AQ49tVJC8JqVxHCnH7
            NcPrzvQjwmlvR71tJSIiSXsvM+fEc1HR7p5TC+3zNHC2fV21n7/wWWL9R6Ppbbum
            GTR2447G7k+c1wYMRnn4A4adq98F9uso33f4qUhl0ueb4poby5Vm8CZ+3jTB9hDU
            aAEJAhA8k403mHP0N4cUqAQKT+6gKDsLt6NzvTPXGuMWlOtcb2uj6fs/zosWvO+R
            xCIme873v7CSNlxKuLGLWa3akbnKveIsYl2KXocJ1llprZoVcYoG2VtQasmPzOWm
            nCBZRdA1h36s
            =JVfj
            -----END PGP MESSAGE-----
          fp: 32B974509BC4B9DD570AB0E8067EBF5DA6F0220A
    encrypted_suffix: stringData
    version: 3.7.2
