apiVersion: gitopssecret.snappcloud.io/v1alpha1
kind: GPGKey
metadata:
  name: gpgkey-sample
  namespace: default
spec:
  armored_private_key: |
    lQdGBGLfrqkBEACsBJyV/gHfQxXXBxNrn5XrezkMj5bLOsjG6ZB7Bp3L7BLLXg4r
    fwSXXI+rlU3slMd6ZGjpGhhJNBp+0u+84p2sucXTZ14zEOdgTOaoKVBgWyiHXOe8
    xILu625vJfBSkJeHDrp1YTJHboHWhTrY1nX5nqPzGICLewY+yQqfZgzHRnoFwQdw
    7B0MjYiUZKnhAjieq1hVirWLk6w9LDaZFbh7ih7GkOk5ll5Em3FJHIDkCdzJvgEu
    XEEkhBdcNlO6FL54WN/U9sMVQxhvF37SfO9ZxYNK9V2KkJewYbsqR22AY/5CLOE1
    Lniy8nzJypEbLpxcC6CAP3QVCVU7fDXDL//8DSkrB8OnYcKRzZFujqJq5YyWeO3M
    uUwDro/ED4LRAwQzjydkGCiRcBfFloay9k0gmGMceQXfrbTu31XyQ/8VAgBxGzzx
    73l4RuF1TwBqUWJUA6htF8jisAuHADMH2AWHHuKbhhi+3/lHd/eZFuWqW+B9Fvpi
    Yky2CWtGYHsrHukPnoOKZAuAUN+OiKTnRGwJyLPoqdLuMq4QDCRxwLv9H2AImNVM
    58ie3nfRyr+VBK0D5IZWKwSVgMZpuOPuuFbMkBUWI6MqQeEcBi9I6tFQGP+2F3hk
    3Vlk5S+0ggNXb55BRAdk2angO0e80Qn12eFD2inac6JFEDYwJRxT70tENQARAQAB
    /gcDAnrvd8sHPiOx+8vBKAZ5t4E3C2BSzjgcNAGuDXPkv/NsyyebIL8bsGTpO8s7
    syxzykMoTvou8uVMleBJuHRCjfOFlBoDvxcJX/OreXQTMSqMPhOwXmr4exVfEDr9
    A5pOfM743SPivWdUa1BmhOAGzdSJgHOcCXrx5e0iSPgmTgKd8PyoDOtW36Ui9v72
    wqZeHUsOh5PIQb8Sw/G8GRCa56GMBNDRBtj0qlaxjf8CMiSQnUTkclDIT3X/jUz0
    47zytuv0TsKOE6ySD302Wc0b2QoTYJr5BOdmoDdDpuSjQM2qwnnC//3GAsaPuUtP
    iW4+tLQO+ThKtHIHCUy0VeBq4qWpuk3AU/LPE8kDKBx353YLIuEtvo8apZAlZIeX
    CsUMC/0eHDb42sDwcqqddBPyGdvXz4QpG8MJuDy7ht7HPYjzLavdvU46FP0sKNkP
    l9vIKCEkOBH99gbGksph51wAhV29vs31N16t930Jc4+LDYTZqrRKR8oEuNJ+pPg1
    9/frfFo7r5xZ0aYyE4YZGKXRLmX3rhDXLUafC9Ko+PnJ2kS8/Vo153bG+xo+G8lw
    vyYYJduJi0NU2GUN9MT5k/F7CYKhZhRdjsUJ8IVhDJJ97mejrosefFdMPQWJIN8C
    AiCljeHsvFzcIP0bH96GGSvHd2qE9M/toNr2AHBDIEVvfxD1sp5McJAduUh6Y2t6
    uDa7WAJdOuI0npHXmCT21SwXosNB2YSrvkDSbEYwzmIAzMJuaeemiKe9Y1rrIOFb
    XszAFbASY+6HC1/q49xp5OWcj9rxAJYTa1oE1TXNoXkI6q4ZZVLvfBEuw5pVTNXP
    4df3ozULsoZWBnliKlLz1rc2nG+tGZYQyvBXY9Xfn1l9+HJtbYO806UbAqnRusSP
    +xjCLDimrEwnDwJ3rEEpevtA3WGU3JuxbDjqPM+fMnbPPFKxrTHUyrHMY25dL6t4
    iRtgooiEiS6raQW9CXuNx8cfAsftXDrPyeAeEP+CzeUpHlJQ/WaIkR16DLcG9fZS
    YSF9TsMjvTxOrXfXSR6DUAmQp+mLMGS4L+hGLGDRpic+a3NaQGjOkwt8opHYQe7B
    +cX0KSLxwHnK9O16mHkSDwNXuUOwv7gVLKrQfcNguACDh55kVmyjpOgUeqPSX2z1
    +n9/gq+758qq5d60G4xkC6WoKNd6fiSWHDVS1vODzj9Gv5WypQbhll/5gQe+0ei3
    tOcJ2i69ZSQcERzjwyZq4tLXf8jEt2QggFzO34Yqwp88dMXFs+PT1uANc3irE30I
    1ZJKm7gX8yqyy0Zmyhz7c7oQcQ+ZlIQFxsmrmEkXffq9ssx3NvB2e8SPZnCFXzar
    v2mW0NQDC1T3lnBQJtOf1MUZYnJFkkYstG7z4RGCD7VL4xFaZGxbnMvnWlcoVhkq
    1LbX1P81XISdRZ0bwJGxPBF7Ro3SvvzLP+A51tIjAypm40uqgNc6Kc9psLEiB4cE
    EpPX2u7Z4zXA8IsRFyxQcQl8/RZ6ht9MlI2fTOzqKUUeR+bVfLQwpYH/LwqtzlCJ
    0esBosCXEpm6qrlKemfO+7x3ZGa5haOXOVD2g8JwU6lDiy+g5+dj9tokhtPJ/Eku
    rBWJpggo55Z1MNCSIhEggn17O529u3AfcabxRme1RKAr1+wu28CpODJSDgjVjvDq
    nHjKrcEsp0of6eWxHUe0aXoDqGvapMbQ2svtvAkagqrJgt5DcDXBwc8sZV+WCTkn
    PJFSyc6xhLAnpsr9t581vtGutNupDG55AI0o5z0kiO1esgCV5b6QBrC0GnRlc3Rn
    cGdrZXkgPHRlc3RAdGVzdC5jb20+iQJRBBMBCAA7FiEEMrl0UJvEud1XCrDoBn6/
    XabwIgoFAmLfrqkCGy8FCwkIBwICIgIGFQoJCAsCBBYCAwECHgcCF4AACgkQBn6/
    XabwIgrDnRAAjdvZp5WXYREVCHKc2DIoFReFgHW7GMfUPWU2jFvMjSjFn2EAkFo/
    fsG6eEGvV4Itn+Pkz1e9F2zziwsR6Nlhs/DydU1youEqibxL/nqhK/Lxi2YixOqe
    X+GPhsNuhRPGFtU25jY4lv1YOJPCXncfph898tNUjY8ny5GwURPJ7oYLdiNOmKJL
    UVTeMP6prYtXT67XS7v0+vhgErsQjak/BuHCZzOyiIAkMkc1Qz4s9lLjvziQFTH6
    T0SjExIy9xk+jXKS5npW+O9oSGVZAYNWH7lutPcFUgV7Z6AGc+DXubW5bFhXgvbM
    ZFogRkZImPTGwE+RvKcRFb/Ku0wDL7UKpCHY67en6Ojuc6NF4hoNPDWtmbvcYSAq
    Cr9d6N54hxa3fJtGVezvIYZp61uFswumlTU43NoYu3a5QreurWAOtwKIGvEvMc9R
    1K9RkDyiSRn/DfK8n99krpPp7ai7dr5idj/Ee2XstGcrQdfv6nzHV3iY82NEAcZ3
    IDpanV2WjVG8jm14PX0FZgS9ayMJjWq9OQOw8XHsxQvuNoTnhJGbwVRLx69sr5j2
    LMh5XN+leccneY9Vp+S8o35XALEx3lRA5Eoa4v3C5bqJ9XYNflP579KF+tVJp/hr
    a3plF/4c/1F2OFJksOYu0cqwRbHR/FuQUKMgNUsIhUNIrEwoNLNS31edB0YEYt+u
    qQEQAOLY48zTS96DV+mddcU0dvSVlIlPwN6bow7yzxqbms+yQ7yC6aQoTGSqBOSb
    i5XaOVdxAh31NsBEcmVmAxfkU87kChtIqa7cfmOO4RgG94ek6x0wjrvvKdaWYkzg
    Gk/LbT8CXTyqdgcLm5+O9KdS61yX4kyQzQgc4rBcyGPIcZnUqgrRG1LGHcVKdxTZ
    Ubs7qmmQ/8JntbU1YVtavla+dlpFQA6WzqmWacmURujxWNRnQRRFbHGHOJBplhIc
    V1heyAlhYfHpaBiNvCwFnrzhMSFCFVWGlmRV9AGWp0N0vMtRkMUdvZxz35lPyqWL
    tOFAw2JRlD/PmgNCisweBLjhIGnlzkgOAlDUR6jMvCXsFIv40w/VIqv0hV1xvw3e
    7SrkLkuT73s6CX8dS9yO0Hm6ebSFmXqnHPi00Ge+s0zVhMFI8Ew3wJ2SpZyJccDa
    Jt77yY22AfrMafZk41TuLE5T4I+yHX02rGHlIy5zJNBwhDgTwE/bXQcCjvLhZNsk
    vBs6omXlrNemT9Z6qI3dwJEE42XiKjwGC52/e5VFWt9HAU4T3Yjzm9uUhAZv/Una
    SsphpkT489hQtNUtPiKekJqvehuFmml/2yTfe09rz0+ooWl5YKfTE1mbSVnyEYvY
    POihJ6Y2FNjLkJ3rtFoaBCRQZ61cUHwLuG5pVSS9paa6NnRbABEBAAH+BwMCLEKj
    lUMZV8r7G8p1E//d/JQgx5YcfRM8rKOS8hNMYYzVhedesu5di96Hpm9RNHwNxz9z
    YBtgCrnQiTK4aAbSW/dFU+BZ/SvaP1RHrr8sXy5MTj6fcfzgZrivkYY3ZczCePP/
    EcHYfl4kYx8jq/kCGirktZdxRYuvtDRuiVPPRK5ZHVgYibcwGm2cgZH1aByHxtnR
    eOsD76Clg72XzrOsbrkTZykaKd6rX7R+jVflvCtGL27HwB6eANydTCG7IcbR5iNH
    DP2NpnM9jYAcdq57Rr1Sa+WlFNYrYDHzO/4qdO8oivpeGfwgKzYP0F3vU13vL+O7
    JbjHD/OZu1VdAV/BBdlfOn5DSWW1psvSMTtBoxMTL5rM0KP69luK4RlXh6KiIhcK
    t5P0e+S2YmZHOb3vaheEYLnMhX0LT+lICrkWxtBRHiNwoxfN2fsyisECLqSaqC22
    7EZDdYfbPL9Wcvr6LcRzly0udIp841VABym0SEvcBf123RAM3a1vN7RGo7wP28Mx
    KUmkbWemJ1VC4yt6Lo14uM9qFmI3ZS2oUKKDqLNxq8SKEpkt1XE3/pC1IQO380WN
    MhUhqu/ZjTx09HZuFp/2LVzX484v3ixITWLkQKOWTtnBpxHyf3SdqLkTcvL8MiLo
    re2Bm/7/X7qdiaxDifTyk/sVUcIE66ROYmE6aNJYyNlOLbDS0CjdIYLSMmAYKZ/p
    VkxbnF+BnAacZ9KsyMRhSKHOd63EnlcZCV0ztak6RycGpF4Pw2FT4WGblLk/duNE
    aW3CMGm5QLDSNPo1Yr5w/5CFplGigjHRal9qUYgaDcB0ZjImS2vamZfU+BSCk7fV
    luJkSroWE/xNzReQz7Gnztqim1Hcu7/v2kS1iQS36Cw//CjxkgAQJoJYEHSdfRZX
    CkKB9fjRd2dSHXprs8GUfoD8+2Q/F7ldRmZKE0LyFkOwXpV2B5n/XMMndYTVlCpH
    QtN1VztmmULFbULOGLRD+cU1Oev0TllfwRwVgPmHe86Te5NhUDfpoTqldAuDqnjw
    YalyH2tsXaw3QG8b8H9iMZgkAZufDwOiLCTuryardXe5HTPT7fpKKegdVwbxEZ7E
    cPLHFL6Rk0gEJkNXQVjbqusrCLOLCIQN8VFs16SyK2IHhBvrsqhrnsQ/dWfEFmJY
    x4y2Iqi7/OCih1Pq+oOeo/uGKVfPMyLKMMGnt+hqZeY2LzBGKL/G78vqdskbsDKS
    It+ue6SQDfPJTCDIUFuUdFpmrTsi04K3YDlnFOh/mRrWKErUaVyQmtCih9sCnaaa
    NTIdfhM8AQPLa4YeLtnSBSOzkk4MZv2HBBROvTJmctLMo6iBCAO9wexQLXz9dOyQ
    2oaSRKXl6cd2X61p1jWiRZ3eI+nq3JEHsM6p/vKasiScRu6q5+xhPqFY1yq23NCu
    JJZ4Ma7aini0luqb3SwJmuzEVmMdAi+H/N8WVken4ndywcjRB3Zc6wVVj1Ne7udx
    Wh6I1V2OhwerMeYfv3rQ0dNCkOf7nSJOp7lxbDnimoxLqzV/pRslcxyRW3YmFtGx
    oUR94ku+NEP/o7jRc8rfbbnMwmkNw7PN39FdzEE94f0ZzXldLBrDLK2I7Vt0h37M
    +Eg/9aU4PuY6EYDGx4HLfpzaA0caknhQojBH30Hm38XTCHDHZsX7rrU/dyV9Wjwd
    UCE7L01EA+sX1lDyJCKZRozrm9QYNqVtylRRcg95lfpRCl68tZ47+mdNytPW8rqk
    Q3T5tD6ShXDTcadcPN3IHsJ0V+Dkv8RWXyBPAWv2qXwqnYkEbAQYAQgAIBYhBDK5
    dFCbxLndVwqw6AZ+v12m8CIKBQJi366pAhsuAkAJEAZ+v12m8CIKwXQgBBkBCAAd
    FiEE/qe3a4GvF00Gq4iGQh0duguflm4FAmLfrqkACgkQQh0duguflm77Bw//eFVD
    PuKSUabMkEaL4b33XGZs2DqXCOZlt5aRHJgz9FrWwCs8n0cF0xuXf/gqGNMZ47uo
    aQxB11hPuVbhXyv4wZ0GBngwTDxlxdYhApvAKgLu1duOFCRIvtRzrdFms3Tk4v5f
    QBCkbDnNMKH81q1v82IhU2E8yHa7D8zdxBeAAelqMwiM1u9u3Cz31omCujD6+ORF
    sXjfHmBOoN69hc+vcrVyzrJnQ/8s2idIiYKeZVKZ66P/LpI1gA20jxnsbHoiOj+N
    pPWCOq4NzHC5VX8nL4Cc/qYlRPkgmKUraeVBBA1HYQ+u0rKEdMWhnA0y+imSSKmV
    BI3fqyUnQ94XPiP9kcqecHtsrVLu3Bd78xjB3ltGuYx8CboPB8ZV3+Z2iYfVxUJv
    G/TeglrAR2Kw/GqABIcf9LQSBTRrkBcLXiV/NScVUVjjywi5kNxwutApV8iy9rI8
    CGXARNUoEoxl6xQvzo7NzZlebBDDOBI0go6z6QKqAJzJ08S8J3mre1sotJO3eGfk
    8HWtfZrVtJvgAB8bIAFn0r+M13yDBKfDNYf9bLYGc+Q2fDrkMNN9zxgb+Kwc8qKB
    /LOy2gpUTClFlCYvflhWOV2DV1wImJ53AmL1961+SYvlEQeCj37ppPrhQ5NDNFCv
    7fxbyf/MUSRzQ7xt2mFf9nOPkmdkfck+/P9o/iycihAAnlPZmU4WLSNInfSkdL3N
    JLE+AQWU/f7/MJZQ3crWTAATxGO+IAAemhOtzwue6NJqq7eIxxWIVeX2TSiVuP97
    bAhe/PUMISUWJj8aKplCDDKaUwusw8NbRlYMU/24T6vlSpv5rEhhfFr5xiRiFkJJ
    WBVGg0xpDbSBGeOqkqUgAQW+wDcqGtEI1DADAandRyhniLe5IwRxCyx9qIWJmtEW
    YUMtUHWgtLEOUz29REw7RtTi7hn+wl8WlsL0TS5OjTOxScgg5FQ83Nz6fsf9hdvi
    FqfqRicSGbCDr/qtxsq7wzmpw0kg4jCYqz23Lyx4H3xqZxkGGRZTsmNUeWJK3bqd
    CbtsHtPD9X2aBbnBYZLmSvpnuUzCQW/Qzn5Wm5/qKpcwN2pxCINvZ57I/EFhy5qt
    qptlr9cK3FczCLmGPIDT9Ri6nUrm5KcMxxIjbq8Ax+Mzk+Y5EW9d3deLpx3fmEEM
    MStAMyYPO/L5Vkl8A5tl4sgT/w8wzBmRH/IePqjmubkVsHJluQ4n3TQbF5x5SfoW
    dCc1jbonckiZyu3be5WFTgkToFFU6kKXloE7F3Hzt2BKv4wHrum1wVnm3tN27DRp
    4HbMb7LmICpZ2hssGUFmnpJsYwMZYIv4lgAQbHGjBmufTAMR9GCTd6iwbWSuezam
    MrzSod9X0tumRHrRXJpUFeg=
    =ZmUL
  passphrase: "qwerP@ssw0rdasdf12345"
